In [1]:
# !pip install alpha_vantage

In [2]:
import pandas as pd
import pandas_datareader as dr
import requests
import json
from sqlalchemy import create_engine
import numpy as np
%matplotlib inline
from sqlalchemy import create_engine

In [3]:
s_p = ['A',
'AAL',
'AAP',
'AAPL',
'ABBV',
'ABC',
'ABMD',
'ABT',
'ACN',
'ADBE',
'ADI',
'ADM',
'ADP',
'ADSK',
'AEE',
'AEP',
'AES',
'AFL',
'AIG',
'AIV',
'AIZ',
'AJG',
'AKAM',
'ALB',
'ALGN',
'ALK',
'ALL',
'ALLE',
'ALXN',
'AMAT',
'AMCR',
'AMD',
'AME',
'AMGN',
'AMP',
'AMT',
'AMZN',
'ANET',
'ANSS',
'ANTM',
'AON',
'AOS',
'APA',
'APD',
'APH',
'APTV',
'ARE',
'ATO',
'ATVI',
'AVB',
'AVGO',
'AVY',
'AWK',
'AXP',
'AZO',
'BA',
'BAC',
'BAX',
'BBY',
'BDX',
'BEN',
'BF.B',
'BIIB',
'BIO',
'BK',
'BKNG',
'BKR',
'BLK',
'BLL',
'BMY',
'BR',
'BRK.B',
'BSX',
'BWA',
'BXP',
'C',
'CAG',
'CAH',
'CARR',
'CAT',
'CB',
'CBOE',
'CBRE',
'CCI',
'CCL',
'CDNS',
'CDW',
'CE',
'CERN',
'CF',
'CFG',
'CHD',
'CHRW',
'CHTR',
'CI',
'CINF',
'CL',
'CLX',
'CMA',
'CMCSA',
'CME',
'CMG',
'CMI',
'CMS',
'CNC',
'CNP',
'COF',
'COG',
'COO',
'COP',
'COST',
'COTY',
'CPB',
'CPRT',
'CRM',
'CSCO',
'CSX',
'CTAS',
'CTL',
'CTSH',
'CTVA',
'CTXS',
'CVS',
'CVX',
'CXO',
'D',
'DAL',
'DD',
'DE',
'DFS',
'DG',
'DGX',
'DHI',
'DHR',
'DIS',
'DISCA',
'DISCK',
'DISH',
'DLR',
'DLTR',
'DOV',
'DOW',
'DPZ',
'DRE',
'DRI',
'DTE',
'DUK',
'DVA',
'DVN',
'DXC',
'DXCM',
'EA',
'EBAY',
'ECL',
'ED',
'EFX',
'EIX',
'EL',
'EMN',
'EMR',
'EOG',
'EQIX',
'EQR',
'ES',
'ESS',
'ETFC',
'ETN',
'ETR',
'EVRG',
'EW',
'EXC',
'EXPD',
'EXPE',
'EXR',
'F',
'FANG',
'FAST',
'FB',
'FBHS',
'FCX',
'FDX',
'FE',
'FFIV',
'FIS',
'FISV',
'FITB',
'FLIR',
'FLS',
'FLT',
'FMC',
'FOX',
'FOXA',
'FRC',
'FRT',
'FTI',
'FTNT',
'FTV',
'GD',
'GE',
'GILD',
'GIS',
'GL',
'GLW',
'GM',
'GOOG',
'GOOGL',
'GPC',
'GPN',
'GPS',
'GRMN',
'GS',
'GWW',
'HAL',
'HAS',
'HBAN',
'HBI',
'HCA',
'HD',
'HES',
'HFC',
'HIG',
'HII',
'HLT',
'HOLX',
'HON',
'HPE',
'HPQ',
'HRB',
'HRL',
'HSIC',
'HST',
'HSY',
'HUM',
'HWM',
'IBM',
'ICE',
'IDXX',
'IEX',
'IFF',
'ILMN',
'INCY',
'INFO',
'INTC',
'INTU',
'IP',
'IPG',
'IPGP',
'IQV',
'IR',
'IRM',
'ISRG',
'IT',
'ITW',
'IVZ',
'J',
'JBHT',
'JCI',
'JKHY',
'JNJ',
'JNPR',
'JPM',
'K',
'KEY',
'KEYS',
'KHC',
'KIM',
'KLAC',
'KMB',
'KMI',
'KMX',
'KO',
'KR',
'KSS',
'KSU',
'L',
'LB',
'LDOS',
'LEG',
'LEN',
'LH',
'LHX',
'LIN',
'LKQ',
'LLY',
'LMT',
'LNC',
'LNT',
'LOW',
'LRCX',
'LUV',
'LVS',
'LW',
'LYB',
'LYV',
'MA',
'MAA',
'MAR',
'MAS',
'MCD',
'MCHP',
'MCK',
'MCO',
'MDLZ',
'MDT',
'MET',
'MGM',
'MHK',
'MKC',
'MKTX',
'MLM',
'MMC',
'MMM',
'MNST',
'MO',
'MOS',
'MPC',
'MRK',
'MRO',
'MS',
'MSCI',
'MSFT',
'MSI',
'MTB',
'MTD',
'MU',
'MXIM',
'MYL',
'NBL',
'NCLH',
'NDAQ',
'NEE',
'NEM',
'NFLX',
'NI',
'NKE',
'NLOK',
'NLSN',
'NOC',
'NOV',
'NOW',
'NRG',
'NSC',
'NTAP',
'NTRS',
'NUE',
'NVDA',
'NVR',
'NWL',
'NWS',
'NWSA',
'O',
'ODFL',
'OKE',
'OMC',
'ORCL',
'ORLY',
'OTIS',
'OXY',
'PAYC',
'PAYX',
'PBCT',
'PCAR',
'PEAK',
'PEG',
'PEP',
'PFE',
'PFG',
'PG',
'PGR',
'PH',
'PHM',
'PKG',
'PKI',
'PLD',
'PM',
'PNC',
'PNR',
'PNW',
'PPG',
'PPL',
'PRGO',
'PRU',
'PSA',
'PSX',
'PVH',
'PWR',
'PXD',
'PYPL',
'QCOM',
'QRVO',
'RCL',
'RE',
'REG',
'REGN',
'RF',
'RHI',
'RJF',
'RL',
'RMD',
'ROK',
'ROL',
'ROP',
'ROST',
'RSG',
'RTX',
'SBAC',
'SBUX',
'SCHW',
'SEE',
'SHW',
'SIVB',
'SJM',
'SLB',
'SLG',
'SNA',
'SNPS',
'SO',
'SPG',
'SPGI',
'SRE',
'STE',
'STT',
'STX',
'STZ',
'SWK',
'SWKS',
'SYF',
'SYK',
'SYY',
'T',
'TAP',
'TDG',
'TDY',
'TEL',
'TFC',
'TFX',
'TGT',
'TIF',
'TJX',
'TMO',
'TMUS',
'TPR',
'TROW',
'TRV',
'TSCO',
'TSN',
'TT',
'TTWO',
'TWTR',
'TXN',
'TXT',
'TYL',
'UA',
'UAA',
'UAL',
'UDR',
'UHS',
'ULTA',
'UNH',
'UNM',
'UNP',
'UPS',
'URI',
'USB',
'V',
'VAR',
'VFC',
'VIAC',
'VLO',
'VMC',
'VNO',
'VRSK',
'VRSN',
'VRTX',
'VTR',
'VZ',
'WAB',
'WAT',
'WBA',
'WDC',
'WEC',
'WELL',
'WFC',
'WHR',
'WLTW',
'WM',
'WMB',
'WMT',
'WRB',
'WRK',
'WST',
'WU',
'WY',
'WYNN',
'XEL',
'XLNX',
'XOM',
'XRAY',
'XRX',
'XYL',
'YUM',
'ZBH',
'ZBRA',
'ZION',
'ZTS']

In [4]:
df = dr.data.get_data_yahoo(s_p, start='2020-01-01', end='2020-07-31')
df

c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'BDX', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'BF.B', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'BIO', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'BLK', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'BR', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'BRK.B', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'CB', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'CBOE', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'CBRE', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'CDW', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'CMA', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'CME', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'CNC', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'CRM', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'CSCO', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'CVS', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'DG', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'DGX', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'DLR', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'EOG', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'EQIX', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'EVRG', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'EXPD', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'FBHS', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'FCX', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'FE', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'FLIR', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'FLT', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'FTI', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'GD', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'GOOGL', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'GPS', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'HAS', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'HD', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'HII', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'HON', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'IBM', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)

c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'ICE', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'IFF', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'IPGP', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'ISRG', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'IVZ', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'JBHT', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'JKHY', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'K', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'KEYS', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'KMI', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'KR', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'KSU', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'LHX', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'LKQ', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'MAA', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'MDLZ', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'MET', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'MHK', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'MMC', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'MS', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'NBL', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'NDAQ', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'NEE', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'NEM', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'NFLX', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'NLSN', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'NOC', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'NOV', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'NVDA', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'NVR', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'ODFL', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'OMC', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'PAYC', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'PCAR', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'PG', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'PKG', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'PKI', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)

c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'PNC', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'PPG', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'PPL', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'PRGO', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'PYPL', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'RSG', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'RTX', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'SBAC', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'SEE', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'SIVB', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'SLG', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'SPG', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'STX', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'SYF', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'TAP', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'TDG', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'TDY', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'TEL', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'TMO', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'TXT', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'UDR', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'UNH', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'VIAC', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'VZ', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'WEC', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'WELL', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'WLTW', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'WM', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'WMB', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'WRB', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'WU', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'WYNN', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
c:\users\criselda\appdata\local\programs\python\python38-32\lib\site-packages\pandas_datareader\base.py:272: SymbolWarning: Failed to read symbol: 'XRX', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)

Attributes  Adj Close                                                \
Symbols             A        AAL         AAP        AAPL       ABBV
Date
2020-01-02  85.552170  28.982893  158.410934  298.292145  86.008141
2020-01-03  84.178558  27.548195  158.420868  295.392120  85.191757
2020-01-06  84.427406  27.219410  155.817291  297.745880  85.864067
2020-01-07  84.686203  27.119778  153.968964  296.345581  85.374245
2020-01-08  85.522316  27.737495  152.200104  301.112640  85.979324
...               ...        ...         ...         ...        ...
2020-07-27  97.269997  11.390000  146.830002  378.557434  97.160004
2020-07-28  95.300003  11.770000  146.190002  372.338684  96.709999
2020-07-29  97.099998  11.400000  148.210007  379.475800  97.010002
2020-07-30  95.930000  11.180000  152.869995  384.067535  96.040001
2020-07-31  96.330002  11.120000  150.139999  424.275024  94.910004

Attributes                                                              ...  \
Symbols            ABC        ABMD         ABT         ACN        ADBE  ...
Date                                                                    ...
2020-01-02   84.283539  168.809998   85.885757  207.639603  334.429993  ...
2020-01-03   83.223557  166.820007   84.838737  207.293793  331.809998  ...
2020-01-06   84.442039  179.039993   85.283234  205.940170  333.709991  ...
2020-01-07   83.837746  180.350006   84.809113  201.493912  333.390015  ...
2020-01-08   84.650070  178.690002   85.154816  201.889160  337.869995  ...
...                ...         ...         ...         ...         ...  ...
2020-07-27  104.000000  298.609985   99.989998  223.320007  437.100006  ...
2020-07-28  102.110001  294.890015   99.860001  222.179993  432.260010  ...
2020-07-29  103.309998  299.100006  102.519997  224.380005  436.299988  ...
2020-07-30  102.169998  298.910004  101.529999  223.979996  438.880005  ...
2020-07-31  100.190002  299.940002  100.639999  224.779999  444.320007  ...

Attributes Volume
Symbols        VZ WEC WELL WLTW  WM WMB WRB  WU WYNN XRX
Date
2020-01-02    NaN NaN  NaN  NaN NaN NaN NaN NaN  NaN NaN
2020-01-03    NaN NaN  NaN  NaN NaN NaN NaN NaN  NaN NaN
2020-01-06    NaN NaN  NaN  NaN NaN NaN NaN NaN  NaN NaN
2020-01-07    NaN NaN  NaN  NaN NaN NaN NaN NaN  NaN NaN
2020-01-08    NaN NaN  NaN  NaN NaN NaN NaN NaN  NaN NaN
...           ...  ..  ...  ...  ..  ..  ..  ..  ...  ..
2020-07-27    NaN NaN  NaN  NaN NaN NaN NaN NaN  NaN NaN
2020-07-28    NaN NaN  NaN  NaN NaN NaN NaN NaN  NaN NaN
2020-07-29    NaN NaN  NaN  NaN NaN NaN NaN NaN  NaN NaN
2020-07-30    NaN NaN  NaN  NaN NaN NaN NaN NaN  NaN NaN
2020-07-31    NaN NaN  NaN  NaN NaN NaN NaN NaN  NaN NaN

[147 rows x 3030 columns]

In [5]:
#Check data types
df.dtypes

Attributes  Symbols
Adj Close   A          float64
            AAL        float64
            AAP        float64
            AAPL       float64
            ABBV       float64
                        ...
Volume      WMB        float64
            WRB        float64
            WU         float64
            WYNN       float64
            XRX        float64
Length: 3030, dtype: object

In [6]:
# df= df.columns.map(''.join)
# df

In [7]:
df.to_csv('yahoo_multicompany_stocks.csv')

In [8]:
df1 = pd.read_csv('yahoo_multicompany_stocks2.csv')  
df1.head()

,Date,Adj Close-Attributes,Adj Close-A,Adj Close-AAL,Adj Close-AAP,Adj Close-AAPL,Adj Close-ABBV,Adj Close-ABC,Adj Close-ABMD,Adj Close-ABT,...,Volume-VZ,Volume-WEC,Volume-WELL,Volume-WLTW,Volume-WM,Volume-WMB,Volume-WRB,Volume-WU,Volume-WYNN,Volume-XRX
0,1/2/2020,Adj Close,85.552170,28.982893,158.410934,298.292145,86.008141,84.283539,168.809998,85.885757,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/3/2020,Adj Close,84.178558,27.548195,158.420868,295.392120,85.191757,83.223557,166.820007,84.838737,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/6/2020,Adj Close,84.427406,27.219410,155.817291,297.745880,85.864067,84.442039,179.039993,85.283234,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/7/2020,Adj Close,84.686203,27.119778,153.968964,296.345581,85.374245,83.837746,180.350006,84.809113,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/8/2020,Adj Close,85.522316,27.737495,152.200104,301.112640,85.979324,84.650070,178.690002,85.154816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df1.set_index('Date')
df1.head()

,Date,Adj Close-Attributes,Adj Close-A,Adj Close-AAL,Adj Close-AAP,Adj Close-AAPL,Adj Close-ABBV,Adj Close-ABC,Adj Close-ABMD,Adj Close-ABT,...,Volume-VZ,Volume-WEC,Volume-WELL,Volume-WLTW,Volume-WM,Volume-WMB,Volume-WRB,Volume-WU,Volume-WYNN,Volume-XRX
0,1/2/2020,Adj Close,85.552170,28.982893,158.410934,298.292145,86.008141,84.283539,168.809998,85.885757,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/3/2020,Adj Close,84.178558,27.548195,158.420868,295.392120,85.191757,83.223557,166.820007,84.838737,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/6/2020,Adj Close,84.427406,27.219410,155.817291,297.745880,85.864067,84.442039,179.039993,85.283234,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/7/2020,Adj Close,84.686203,27.119778,153.968964,296.345581,85.374245,83.837746,180.350006,84.809113,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/8/2020,Adj Close,85.522316,27.737495,152.200104,301.112640,85.979324,84.650070,178.690002,85.154816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
adj_df = df1.iloc[:,0:507]

In [11]:
adj_df.dropna(axis=1, how='all', inplace=True)
adj_df.fillna(0)

,Date,Adj Close-Attributes,Adj Close-A,Adj Close-AAL,Adj Close-AAP,Adj Close-AAPL,Adj Close-ABBV,Adj Close-ABC,Adj Close-ABMD,Adj Close-ABT,...,Adj Close-XEL,Adj Close-XLNX,Adj Close-XOM,Adj Close-XRAY,Adj Close-XYL,Adj Close-YUM,Adj Close-ZBH,Adj Close-ZBRA,Adj Close-ZION,Adj Close-ZTS
0,1/2/2020,Adj Close,85.552170,28.982893,158.410934,298.292145,86.008141,84.283539,168.809998,85.885757,...,61.569065,100.765846,68.567070,56.634895,79.849998,101.184380,148.520401,259.140015,51.462421,133.542831
1,1/3/2020,Adj Close,84.178558,27.548195,158.420868,295.392120,85.191757,83.223557,166.820007,84.838737,...,61.865166,98.446198,68.015823,56.008160,80.320000,100.867470,148.132172,256.049988,50.736221,133.562759
2,1/6/2020,Adj Close,84.427406,27.219410,155.817291,297.745880,85.864067,84.442039,179.039993,85.283234,...,61.776337,96.394203,68.538055,56.316555,79.800003,100.808052,147.276093,258.010010,50.117962,132.537338
3,1/7/2020,Adj Close,84.686203,27.119778,153.968964,296.345581,85.374245,83.837746,180.350006,84.809113,...,61.648026,98.594894,67.977135,56.614998,79.500000,100.986313,147.146683,256.470001,49.813740,132.985321
4,1/8/2020,Adj Close,85.522316,27.737495,152.200104,301.112640,85.979324,84.650070,178.690002,85.154816,...,61.588806,98.317329,66.952019,57.211887,79.769997,101.164581,148.908630,247.639999,50.304417,132.696609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,7/27/2020,Adj Close,97.269997,11.390000,146.830002,378.557434,97.160004,104.000000,298.609985,99.989998,...,67.510002,106.809998,44.070000,43.450001,75.260002,93.370003,134.240005,273.339996,32.410000,146.919998
143,7/28/2020,Adj Close,95.300003,11.770000,146.190002,372.338684,96.709999,102.110001,294.890015,99.860001,...,68.370003,104.809998,43.549999,43.500000,74.339996,92.750000,134.160004,271.179993,32.259998,145.979996
144,7/29/2020,Adj Close,97.099998,11.400000,148.210007,379.475800,97.010002,103.309998,299.100006,102.519997,...,68.730003,107.820000,44.029999,44.790001,77.169998,94.830002,139.580002,273.850006,33.369999,147.589996
145,7/30/2020,Adj Close,95.930000,11.180000,152.869995,384.067535,96.040001,102.169998,298.910004,101.529999,...,69.000000,111.870003,41.869999,45.240002,74.669998,91.639999,138.300003,274.950012,32.779999,149.110001
146,7/31/2020,Adj Close,96.330002,11.120000,150.139999,424.275024,94.910004,100.190002,299.940002,100.639999,...,69.040001,107.349999,42.080002,44.599998,72.980003,91.050003,134.860001,280.750000,32.470001,151.679993

In [12]:
adj_df.columns = adj_df.columns.str.replace('Adj Close-','')
adj_df

,Date,Attributes,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
0,1/2/2020,Adj Close,85.552170,28.982893,158.410934,298.292145,86.008141,84.283539,168.809998,85.885757,...,61.569065,100.765846,68.567070,56.634895,79.849998,101.184380,148.520401,259.140015,51.462421,133.542831
1,1/3/2020,Adj Close,84.178558,27.548195,158.420868,295.392120,85.191757,83.223557,166.820007,84.838737,...,61.865166,98.446198,68.015823,56.008160,80.320000,100.867470,148.132172,256.049988,50.736221,133.562759
2,1/6/2020,Adj Close,84.427406,27.219410,155.817291,297.745880,85.864067,84.442039,179.039993,85.283234,...,61.776337,96.394203,68.538055,56.316555,79.800003,100.808052,147.276093,258.010010,50.117962,132.537338
3,1/7/2020,Adj Close,84.686203,27.119778,153.968964,296.345581,85.374245,83.837746,180.350006,84.809113,...,61.648026,98.594894,67.977135,56.614998,79.500000,100.986313,147.146683,256.470001,49.813740,132.985321
4,1/8/2020,Adj Close,85.522316,27.737495,152.200104,301.112640,85.979324,84.650070,178.690002,85.154816,...,61.588806,98.317329,66.952019,57.211887,79.769997,101.164581,148.908630,247.639999,50.304417,132.696609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,7/27/2020,Adj Close,97.269997,11.390000,146.830002,378.557434,97.160004,104.000000,298.609985,99.989998,...,67.510002,106.809998,44.070000,43.450001,75.260002,93.370003,134.240005,273.339996,32.410000,146.919998
143,7/28/2020,Adj Close,95.300003,11.770000,146.190002,372.338684,96.709999,102.110001,294.890015,99.860001,...,68.370003,104.809998,43.549999,43.500000,74.339996,92.750000,134.160004,271.179993,32.259998,145.979996
144,7/29/2020,Adj Close,97.099998,11.400000,148.210007,379.475800,97.010002,103.309998,299.100006,102.519997,...,68.730003,107.820000,44.029999,44.790001,77.169998,94.830002,139.580002,273.850006,33.369999,147.589996
145,7/30/2020,Adj Close,95.930000,11.180000,152.869995,384.067535,96.040001,102.169998,298.910004,101.529999,...,69.000000,111.870003,41.869999,45.240002,74.669998,91.639999,138.300003,274.950012,32.779999,149.110001
146,7/31/2020,Adj Close,96.330002,11.120000,150.139999,424.275024,94.910004,100.190002,299.940002,100.639999,...,69.040001,107.349999,42.080002,44.599998,72.980003,91.050003,134.860001,280.750000,32.470001,151.679993

In [13]:
adj_df.to_csv('yahoo_adj_df.csv')

In [14]:
closeslice_list = ['Date',	'Close-Attributes',	'Close-A',	'Close-AAL',	'Close-AAP',	'Close-AAPL',	'Close-ABBV',	'Close-ABC',	'Close-ABMD',	'Close-ABT',	'Close-ACN',	'Close-ADBE',	'Close-ADI',	'Close-ADM',	'Close-ADP',	'Close-ADSK',	'Close-AEE',	'Close-AEP',	'Close-AES',	'Close-AFL',	'Close-AIG',	'Close-AIV',	'Close-AIZ',	'Close-AJG',	'Close-AKAM',	'Close-ALB',	'Close-ALGN',	'Close-ALK',	'Close-ALL',	'Close-ALLE',	'Close-ALXN',	'Close-AMAT',	'Close-AMCR',	'Close-AMD',	'Close-AME',	'Close-AMGN',	'Close-AMP',	'Close-AMT',	'Close-AMZN',	'Close-ANET',	'Close-ANSS',	'Close-ANTM',	'Close-AON',	'Close-AOS',	'Close-APA',	'Close-APD',	'Close-APH',	'Close-APTV',	'Close-ARE',	'Close-ATO',	'Close-ATVI',	'Close-AVB',	'Close-AVGO',	'Close-AVY',	'Close-AWK',	'Close-AXP',	'Close-AZO',	'Close-BA',	'Close-BAC',	'Close-BAX',	'Close-BBY',	'Close-BEN',	'Close-BIIB',	'Close-BK',	'Close-BKNG',	'Close-BKR',	'Close-BLL',	'Close-BMY',	'Close-BSX',	'Close-BWA',	'Close-BXP',	'Close-C',	'Close-CAG',	'Close-CAH',	'Close-CARR',	'Close-CAT',	'Close-CCI',	'Close-CCL',	'Close-CDNS',	'Close-CE',	'Close-CERN',	'Close-CF',	'Close-CFG',	'Close-CHD',	'Close-CHRW',	'Close-CHTR',	'Close-CI',	'Close-CINF',	'Close-CL',	'Close-CLX',	'Close-CMCSA',	'Close-CMG',	'Close-CMI',	'Close-CMS',	'Close-CNP',	'Close-COF',	'Close-COG',	'Close-COO',	'Close-COP',	'Close-COST',	'Close-COTY',	'Close-CPB',	'Close-CPRT',	'Close-CSX',	'Close-CTAS',	'Close-CTL',	'Close-CTSH',	'Close-CTVA',	'Close-CTXS',	'Close-CVX',	'Close-CXO',	'Close-D',	'Close-DAL',	'Close-DD',	'Close-DE',	'Close-DFS',	'Close-DHI',	'Close-DHR',	'Close-DIS',	'Close-DISCA',	'Close-DISCK',	'Close-DISH',	'Close-DLTR',	'Close-DOV',	'Close-DOW',	'Close-DPZ',	'Close-DRE',	'Close-DRI',	'Close-DTE',	'Close-DUK',	'Close-DVA',	'Close-DVN',	'Close-DXC',	'Close-DXCM',	'Close-EA',	'Close-EBAY',	'Close-ECL',	'Close-ED',	'Close-EFX',	'Close-EIX',	'Close-EL',	'Close-EMN',	'Close-EMR',	'Close-EQR',	'Close-ES',	'Close-ESS',	'Close-ETFC',	'Close-ETN',	'Close-ETR',	'Close-EW',	'Close-EXC',	'Close-EXPE',	'Close-EXR',	'Close-F',	'Close-FANG',	'Close-FAST',	'Close-FB',	'Close-FDX',	'Close-FFIV',	'Close-FIS',	'Close-FISV',	'Close-FITB',	'Close-FLS',	'Close-FMC',	'Close-FOX',	'Close-FOXA',	'Close-FRC',	'Close-FRT',	'Close-FTNT',	'Close-FTV',	'Close-GE',	'Close-GILD',	'Close-GIS',	'Close-GL',	'Close-GLW',	'Close-GM',	'Close-GOOG',	'Close-GPC',	'Close-GPN',	'Close-GRMN',	'Close-GS',	'Close-GWW',	'Close-HAL',	'Close-HBAN',	'Close-HBI',	'Close-HCA',	'Close-HES',	'Close-HFC',	'Close-HIG',	'Close-HLT',	'Close-HOLX',	'Close-HPE',	'Close-HPQ',	'Close-HRB',	'Close-HRL',	'Close-HSIC',	'Close-HST',	'Close-HSY',	'Close-HUM',	'Close-HWM',	'Close-IDXX',	'Close-IEX',	'Close-ILMN',	'Close-INCY',	'Close-INFO',	'Close-INTC',	'Close-INTU',	'Close-IP',	'Close-IPG',	'Close-IQV',	'Close-IR',	'Close-IRM',	'Close-IT',	'Close-ITW',	'Close-J',	'Close-JCI',	'Close-JNJ',	'Close-JNPR',	'Close-JPM',	'Close-KEY',	'Close-KHC',	'Close-KIM',	'Close-KLAC',	'Close-KMB',	'Close-KMX',	'Close-KO',	'Close-KSS',	'Close-L',	'Close-LB',	'Close-LDOS',	'Close-LEG',	'Close-LEN',	'Close-LH',	'Close-LIN',	'Close-LLY',	'Close-LMT',	'Close-LNC',	'Close-LNT',	'Close-LOW',	'Close-LRCX',	'Close-LUV',	'Close-LVS',	'Close-LW',	'Close-LYB',	'Close-LYV',	'Close-MA',	'Close-MAR',	'Close-MAS',	'Close-MCD',	'Close-MCHP',	'Close-MCK',	'Close-MCO',	'Close-MDT',	'Close-MGM',	'Close-MKC',	'Close-MKTX',	'Close-MLM',	'Close-MMM',	'Close-MNST',	'Close-MO',	'Close-MOS',	'Close-MPC',	'Close-MRK',	'Close-MRO',	'Close-MSCI',	'Close-MSFT',	'Close-MSI',	'Close-MTB',	'Close-MTD',	'Close-MU',	'Close-MXIM',	'Close-MYL',	'Close-NCLH',	'Close-NI',	'Close-NKE',	'Close-NLOK',	'Close-NOW',	'Close-NRG',	'Close-NSC',	'Close-NTAP',	'Close-NTRS',	'Close-NUE',	'Close-NWL',	'Close-NWS',	'Close-NWSA',	'Close-O',	'Close-OKE',	'Close-ORCL',	'Close-ORLY',	'Close-OTIS',	'Close-OXY',	'Close-PAYX',	'Close-PBCT',	'Close-PEAK',	'Close-PEG',	'Close-PEP',	'Close-PFE',	'Close-PFG',	'Close-PGR',	'Close-PH',	'Close-PHM',	'Close-PLD',	'Close-PM',	'Close-PNR',	'Close-PNW',	'Close-PRU',	'Close-PSA',	'Close-PSX',	'Close-PVH',	'Close-PWR',	'Close-PXD',	'Close-QCOM',	'Close-QRVO',	'Close-RCL',	'Close-RE',	'Close-REG',	'Close-REGN',	'Close-RF',	'Close-RHI',	'Close-RJF',	'Close-RL',	'Close-RMD',	'Close-ROK',	'Close-ROL',	'Close-ROP',	'Close-ROST',	'Close-SBUX',	'Close-SCHW',	'Close-SHW',	'Close-SJM',	'Close-SLB',	'Close-SNA',	'Close-SNPS',	'Close-SO',	'Close-SPGI',	'Close-SRE',	'Close-STE',	'Close-STT',	'Close-STZ',	'Close-SWK',	'Close-SWKS',	'Close-SYK',	'Close-SYY',	'Close-T',	'Close-TFC',	'Close-TFX',	'Close-TGT',	'Close-TIF',	'Close-TJX',	'Close-TMUS',	'Close-TPR',	'Close-TROW',	'Close-TRV',	'Close-TSCO',	'Close-TSN',	'Close-TT',	'Close-TTWO',	'Close-TWTR',	'Close-TXN',	'Close-TYL',	'Close-UA',	'Close-UAA',	'Close-UAL',	'Close-UHS',	'Close-ULTA',	'Close-UNM',	'Close-UNP',	'Close-UPS',	'Close-URI',	'Close-USB',	'Close-V',	'Close-VAR',	'Close-VFC',	'Close-VLO',	'Close-VMC',	'Close-VNO',	'Close-VRSK',	'Close-VRSN',	'Close-VRTX',	'Close-VTR',	'Close-WAB',	'Close-WAT',	'Close-WBA',	'Close-WDC',	'Close-WFC',	'Close-WHR',	'Close-WMT',	'Close-WRK',	'Close-WST',	'Close-WY',	'Close-XEL',	'Close-XLNX',	'Close-XOM',	'Close-XRAY',	'Close-XYL',	'Close-YUM',	'Close-ZBH',	'Close-ZBRA',	'Close-ZION',	'Close-ZTS',	'Close-BDX',	'Close-BF.B',	'Close-BIO',	'Close-BLK',	'Close-BR',	'Close-BRK.B',	'Close-CB',	'Close-CBOE',	'Close-CBRE',	'Close-CDW',	'Close-CMA',	'Close-CME',	'Close-CNC',	'Close-CRM',	'Close-CSCO',	'Close-CVS',	'Close-DG',	'Close-DGX',	'Close-DLR',	'Close-EOG',	'Close-EQIX',	'Close-EVRG',	'Close-EXPD',	'Close-FBHS',	'Close-FCX',	'Close-FE',	'Close-FLIR',	'Close-FLT',	'Close-FTI',	'Close-GD',	'Close-GOOGL',	'Close-GPS',	'Close-HAS',	'Close-HD',	'Close-HII',	'Close-HON',	'Close-IBM',	'Close-ICE',	'Close-IFF',	'Close-IPGP',	'Close-ISRG',	'Close-IVZ',	'Close-JBHT',	'Close-JKHY',	'Close-K',	'Close-KEYS',	'Close-KMI',	'Close-KR',	'Close-KSU',	'Close-LHX',	'Close-LKQ',	'Close-MAA',	'Close-MDLZ',	'Close-MET',	'Close-MHK',	'Close-MMC',	'Close-MS',	'Close-NBL',	'Close-NDAQ',	'Close-NEE',	'Close-NEM',	'Close-NFLX',	'Close-NLSN',	'Close-NOC',	'Close-NOV',	'Close-NVDA',	'Close-NVR',	'Close-ODFL',	'Close-OMC',	'Close-PAYC',	'Close-PCAR',	'Close-PG',	'Close-PKG',	'Close-PKI',	'Close-PNC',	'Close-PPG',	'Close-PPL',	'Close-PRGO',	'Close-PYPL',	'Close-RSG',	'Close-RTX',	'Close-SBAC',	'Close-SEE',	'Close-SIVB',	'Close-SLG',	'Close-SPG',	'Close-STX',	'Close-SYF',	'Close-TAP',	'Close-TDG',	'Close-TDY',	'Close-TEL',	'Close-TMO',	'Close-TXT',	'Close-UDR',	'Close-UNH',	'Close-VIAC',	'Close-VZ',	'Close-WEC',	'Close-WELL',	'Close-WLTW',	'Close-WM',	'Close-WMB',	'Close-WRB',	'Close-WU',	'Close-WYNN',	'Close-XRX']
close_df = df1[closeslice_list]
close_df.head()

,Date,Close-Attributes,Close-A,Close-AAL,Close-AAP,Close-AAPL,Close-ABBV,Close-ABC,Close-ABMD,Close-ABT,...,Close-VZ,Close-WEC,Close-WELL,Close-WLTW,Close-WM,Close-WMB,Close-WRB,Close-WU,Close-WYNN,Close-XRX
0,1/2/2020,Close,85.949997,29.090000,159.410004,300.350006,89.550003,85.080002,168.809998,86.949997,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/3/2020,Close,84.570000,27.650000,159.419998,297.429993,88.699997,84.010002,166.820007,85.889999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/6/2020,Close,84.820000,27.320000,156.800003,299.799988,89.400002,85.239998,179.039993,86.339996,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/7/2020,Close,85.080002,27.219999,154.940002,298.390015,88.889999,84.629997,180.350006,85.860001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/8/2020,Close,85.919998,27.840000,153.160004,303.190002,89.519997,85.449997,178.690002,86.209999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
close_df.dropna(axis=1, how='all', inplace=True)
close_df.fillna(0)
close_df.columns = close_df.columns.str.replace('Close-','')
close_df

<ipython-input-15-3c1a9d6a5736>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  close_df.dropna(axis=1, how='all', inplace=True)

,Date,Attributes,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
0,1/2/2020,Close,85.949997,29.090000,159.410004,300.350006,89.550003,85.080002,168.809998,86.949997,...,62.380001,101.650002,70.900002,56.930000,79.849998,102.169998,149.199997,259.140015,52.439999,134.139999
1,1/3/2020,Close,84.570000,27.650000,159.419998,297.429993,88.699997,84.010002,166.820007,85.889999,...,62.680000,99.309998,70.330002,56.299999,80.320000,101.849998,148.809998,256.049988,51.700001,134.160004
2,1/6/2020,Close,84.820000,27.320000,156.800003,299.799988,89.400002,85.239998,179.039993,86.339996,...,62.590000,97.239998,70.870003,56.610001,79.800003,101.790001,147.949997,258.010010,51.070000,133.130005
3,1/7/2020,Close,85.080002,27.219999,154.940002,298.390015,88.889999,84.629997,180.350006,85.860001,...,62.459999,99.459999,70.290001,56.910000,79.500000,101.970001,147.820007,256.470001,50.759998,133.580002
4,1/8/2020,Close,85.919998,27.840000,153.160004,303.190002,89.519997,85.449997,178.690002,86.209999,...,62.400002,99.180000,69.230003,57.509998,79.769997,102.150002,149.589996,247.639999,51.259998,133.289993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,7/27/2020,Close,97.269997,11.390000,146.830002,379.239990,97.160004,104.000000,298.609985,99.989998,...,67.510002,106.809998,44.070000,43.450001,75.260002,93.370003,134.240005,273.339996,32.410000,146.919998
143,7/28/2020,Close,95.300003,11.770000,146.190002,373.010010,96.709999,102.110001,294.890015,99.860001,...,68.370003,104.809998,43.549999,43.500000,74.339996,92.750000,134.160004,271.179993,32.259998,145.979996
144,7/29/2020,Close,97.099998,11.400000,148.210007,380.160004,97.010002,103.309998,299.100006,102.519997,...,68.730003,107.820000,44.029999,44.790001,77.169998,94.830002,139.580002,273.850006,33.369999,147.589996
145,7/30/2020,Close,95.930000,11.180000,152.869995,384.760010,96.040001,102.169998,298.910004,101.529999,...,69.000000,111.870003,41.869999,45.240002,74.669998,91.639999,138.300003,274.950012,32.779999,149.110001
146,7/31/2020,Close,96.330002,11.120000,150.139999,425.040008,94.910004,100.190002,299.940002,100.639999,...,69.040001,107.349999,42.080002,44.599998,72.980003,91.050003,134.860001,280.750000,32.470001,151.679993

In [16]:
close_df.to_csv('yahoo_close_df.csv')

In [17]:
highslice_list = ['Date',	'High-Attributes',	'High-A',	'High-AAL',	'High-AAP',	'High-AAPL',	'High-ABBV',	'High-ABC',	'High-ABMD',	'High-ABT',	'High-ACN',	'High-ADBE',	'High-ADI',	'High-ADM',	'High-ADP',	'High-ADSK',	'High-AEE',	'High-AEP',	'High-AES',	'High-AFL',	'High-AIG',	'High-AIV',	'High-AIZ',	'High-AJG',	'High-AKAM',	'High-ALB',	'High-ALGN',	'High-ALK',	'High-ALL',	'High-ALLE',	'High-ALXN',	'High-AMAT',	'High-AMCR',	'High-AMD',	'High-AME',	'High-AMGN',	'High-AMP',	'High-AMT',	'High-AMZN',	'High-ANET',	'High-ANSS',	'High-ANTM',	'High-AON',	'High-AOS',	'High-APA',	'High-APD',	'High-APH',	'High-APTV',	'High-ARE',	'High-ATO',	'High-ATVI',	'High-AVB',	'High-AVGO',	'High-AVY',	'High-AWK',	'High-AXP',	'High-AZO',	'High-BA',	'High-BAC',	'High-BAX',	'High-BBY',	'High-BEN',	'High-BIIB',	'High-BK',	'High-BKNG',	'High-BKR',	'High-BLL',	'High-BMY',	'High-BSX',	'High-BWA',	'High-BXP',	'High-C',	'High-CAG',	'High-CAH',	'High-CARR',	'High-CAT',	'High-CCI',	'High-CCL',	'High-CDNS',	'High-CE',	'High-CERN',	'High-CF',	'High-CFG',	'High-CHD',	'High-CHRW',	'High-CHTR',	'High-CI',	'High-CINF',	'High-CL',	'High-CLX',	'High-CMCSA',	'High-CMG',	'High-CMI',	'High-CMS',	'High-CNP',	'High-COF',	'High-COG',	'High-COO',	'High-COP',	'High-COST',	'High-COTY',	'High-CPB',	'High-CPRT',	'High-CSX',	'High-CTAS',	'High-CTL',	'High-CTSH',	'High-CTVA',	'High-CTXS',	'High-CVX',	'High-CXO',	'High-D',	'High-DAL',	'High-DD',	'High-DE',	'High-DFS',	'High-DHI',	'High-DHR',	'High-DIS',	'High-DISCA',	'High-DISCK',	'High-DISH',	'High-DLTR',	'High-DOV',	'High-DOW',	'High-DPZ',	'High-DRE',	'High-DRI',	'High-DTE',	'High-DUK',	'High-DVA',	'High-DVN',	'High-DXC',	'High-DXCM',	'High-EA',	'High-EBAY',	'High-ECL',	'High-ED',	'High-EFX',	'High-EIX',	'High-EL',	'High-EMN',	'High-EMR',	'High-EQR',	'High-ES',	'High-ESS',	'High-ETFC',	'High-ETN',	'High-ETR',	'High-EW',	'High-EXC',	'High-EXPE',	'High-EXR',	'High-F',	'High-FANG',	'High-FAST',	'High-FB',	'High-FDX',	'High-FFIV',	'High-FIS',	'High-FISV',	'High-FITB',	'High-FLS',	'High-FMC',	'High-FOX',	'High-FOXA',	'High-FRC',	'High-FRT',	'High-FTNT',	'High-FTV',	'High-GE',	'High-GILD',	'High-GIS',	'High-GL',	'High-GLW',	'High-GM',	'High-GOOG',	'High-GPC',	'High-GPN',	'High-GRMN',	'High-GS',	'High-GWW',	'High-HAL',	'High-HBAN',	'High-HBI',	'High-HCA',	'High-HES',	'High-HFC',	'High-HIG',	'High-HLT',	'High-HOLX',	'High-HPE',	'High-HPQ',	'High-HRB',	'High-HRL',	'High-HSIC',	'High-HST',	'High-HSY',	'High-HUM',	'High-HWM',	'High-IDXX',	'High-IEX',	'High-ILMN',	'High-INCY',	'High-INFO',	'High-INTC',	'High-INTU',	'High-IP',	'High-IPG',	'High-IQV',	'High-IR',	'High-IRM',	'High-IT',	'High-ITW',	'High-J',	'High-JCI',	'High-JNJ',	'High-JNPR',	'High-JPM',	'High-KEY',	'High-KHC',	'High-KIM',	'High-KLAC',	'High-KMB',	'High-KMX',	'High-KO',	'High-KSS',	'High-L',	'High-LB',	'High-LDOS',	'High-LEG',	'High-LEN',	'High-LH',	'High-LIN',	'High-LLY',	'High-LMT',	'High-LNC',	'High-LNT',	'High-LOW',	'High-LRCX',	'High-LUV',	'High-LVS',	'High-LW',	'High-LYB',	'High-LYV',	'High-MA',	'High-MAR',	'High-MAS',	'High-MCD',	'High-MCHP',	'High-MCK',	'High-MCO',	'High-MDT',	'High-MGM',	'High-MKC',	'High-MKTX',	'High-MLM',	'High-MMM',	'High-MNST',	'High-MO',	'High-MOS',	'High-MPC',	'High-MRK',	'High-MRO',	'High-MSCI',	'High-MSFT',	'High-MSI',	'High-MTB',	'High-MTD',	'High-MU',	'High-MXIM',	'High-MYL',	'High-NCLH',	'High-NI',	'High-NKE',	'High-NLOK',	'High-NOW',	'High-NRG',	'High-NSC',	'High-NTAP',	'High-NTRS',	'High-NUE',	'High-NWL',	'High-NWS',	'High-NWSA',	'High-O',	'High-OKE',	'High-ORCL',	'High-ORLY',	'High-OTIS',	'High-OXY',	'High-PAYX',	'High-PBCT',	'High-PEAK',	'High-PEG',	'High-PEP',	'High-PFE',	'High-PFG',	'High-PGR',	'High-PH',	'High-PHM',	'High-PLD',	'High-PM',	'High-PNR',	'High-PNW',	'High-PRU',	'High-PSA',	'High-PSX',	'High-PVH',	'High-PWR',	'High-PXD',	'High-QCOM',	'High-QRVO',	'High-RCL',	'High-RE',	'High-REG',	'High-REGN',	'High-RF',	'High-RHI',	'High-RJF',	'High-RL',	'High-RMD',	'High-ROK',	'High-ROL',	'High-ROP',	'High-ROST',	'High-SBUX',	'High-SCHW',	'High-SHW',	'High-SJM',	'High-SLB',	'High-SNA',	'High-SNPS',	'High-SO',	'High-SPGI',	'High-SRE',	'High-STE',	'High-STT',	'High-STZ',	'High-SWK',	'High-SWKS',	'High-SYK',	'High-SYY',	'High-T',	'High-TFC',	'High-TFX',	'High-TGT',	'High-TIF',	'High-TJX',	'High-TMUS',	'High-TPR',	'High-TROW',	'High-TRV',	'High-TSCO',	'High-TSN',	'High-TT',	'High-TTWO',	'High-TWTR',	'High-TXN',	'High-TYL',	'High-UA',	'High-UAA',	'High-UAL',	'High-UHS',	'High-ULTA',	'High-UNM',	'High-UNP',	'High-UPS',	'High-URI',	'High-USB',	'High-V',	'High-VAR',	'High-VFC',	'High-VLO',	'High-VMC',	'High-VNO',	'High-VRSK',	'High-VRSN',	'High-VRTX',	'High-VTR',	'High-WAB',	'High-WAT',	'High-WBA',	'High-WDC',	'High-WFC',	'High-WHR',	'High-WMT',	'High-WRK',	'High-WST',	'High-WY',	'High-XEL',	'High-XLNX',	'High-XOM',	'High-XRAY',	'High-XYL',	'High-YUM',	'High-ZBH',	'High-ZBRA',	'High-ZION',	'High-ZTS',	'High-BDX',	'High-BF.B',	'High-BIO',	'High-BLK',	'High-BR',	'High-BRK.B',	'High-CB',	'High-CBOE',	'High-CBRE',	'High-CDW',	'High-CMA',	'High-CME',	'High-CNC',	'High-CRM',	'High-CSCO',	'High-CVS',	'High-DG',	'High-DGX',	'High-DLR',	'High-EOG',	'High-EQIX',	'High-EVRG',	'High-EXPD',	'High-FBHS',	'High-FCX',	'High-FE',	'High-FLIR',	'High-FLT',	'High-FTI',	'High-GD',	'High-GOOGL',	'High-GPS',	'High-HAS',	'High-HD',	'High-HII',	'High-HON',	'High-IBM',	'High-ICE',	'High-IFF',	'High-IPGP',	'High-ISRG',	'High-IVZ',	'High-JBHT',	'High-JKHY',	'High-K',	'High-KEYS',	'High-KMI',	'High-KR',	'High-KSU',	'High-LHX',	'High-LKQ',	'High-MAA',	'High-MDLZ',	'High-MET',	'High-MHK',	'High-MMC',	'High-MS',	'High-NBL',	'High-NDAQ',	'High-NEE',	'High-NEM',	'High-NFLX',	'High-NLSN',	'High-NOC',	'High-NOV',	'High-NVDA',	'High-NVR',	'High-ODFL',	'High-OMC',	'High-PAYC',	'High-PCAR',	'High-PG',	'High-PKG',	'High-PKI',	'High-PNC',	'High-PPG',	'High-PPL',	'High-PRGO',	'High-PYPL',	'High-RSG',	'High-RTX',	'High-SBAC',	'High-SEE',	'High-SIVB',	'High-SLG',	'High-SPG',	'High-STX',	'High-SYF',	'High-TAP',	'High-TDG',	'High-TDY',	'High-TEL',	'High-TMO',	'High-TXT',	'High-UDR',	'High-UNH',	'High-VIAC',	'High-VZ',	'High-WEC',	'High-WELL',	'High-WLTW',	'High-WM',	'High-WMB',	'High-WRB',	'High-WU',	'High-WYNN',	'High-XRX']
high_df = df1[highslice_list]
high_df.head()

,Date,High-Attributes,High-A,High-AAL,High-AAP,High-AAPL,High-ABBV,High-ABC,High-ABMD,High-ABT,...,High-VZ,High-WEC,High-WELL,High-WLTW,High-WM,High-WMB,High-WRB,High-WU,High-WYNN,High-XRX
0,1/2/2020,High,86.349998,29.299999,160.949997,300.600006,89.570000,85.800003,173.860001,86.959999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/3/2020,High,85.330002,28.290001,159.630005,300.579987,89.389999,85.070000,169.320007,86.669998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/6/2020,High,84.820000,27.490000,158.889999,299.959992,89.620003,85.309998,179.419998,86.360001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/7/2020,High,85.260002,27.680000,157.399994,300.899994,89.540001,85.250000,182.440002,86.300003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/8/2020,High,86.470001,28.090000,156.050003,304.440002,90.059998,85.820000,180.729996,86.660004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
high_df.dropna(axis=1, how='all', inplace=True)
high_df.fillna(0)
high_df.columns = high_df.columns.str.replace('High-','')
high_df.head()

<ipython-input-18-a728ad18dc32>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  high_df.dropna(axis=1, how='all', inplace=True)

,Date,Attributes,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
0,1/2/2020,High,86.349998,29.299999,160.949997,300.600006,89.570000,85.800003,173.860001,86.959999,...,63.580002,101.690002,71.019997,57.509998,79.949997,102.190002,150.050003,260.399994,52.480000,134.279999
1,1/3/2020,High,85.330002,28.290001,159.630005,300.579987,89.389999,85.070000,169.320007,86.669998,...,62.919998,101.059998,71.370003,56.770000,80.349998,102.010002,149.679993,258.649994,51.889999,134.910004
2,1/6/2020,High,84.820000,27.490000,158.889999,299.959992,89.620003,85.309998,179.419998,86.360001,...,62.939999,98.360001,71.360001,56.680000,79.940002,101.800003,148.830002,258.010010,51.680000,134.070007
3,1/7/2020,High,85.260002,27.680000,157.399994,300.899994,89.540001,85.250000,182.440002,86.300003,...,62.520000,100.150002,70.519997,56.980000,79.910004,102.239998,149.139999,258.739990,51.130001,134.809998
4,1/8/2020,High,86.470001,28.090000,156.050003,304.440002,90.059998,85.820000,180.729996,86.660004,...,62.639999,100.000000,70.290001,57.709999,80.360001,102.980003,149.929993,253.479996,51.490002,135.270004

In [19]:
high_df.to_csv('yahoo_high_df.csv')

In [20]:
lowslice_list = ['Date',	'Low-Attributes',	'Low-A',	'Low-AAL',	'Low-AAP',	'Low-AAPL',	'Low-ABBV',	'Low-ABC',	'Low-ABMD',	'Low-ABT',	'Low-ACN',	'Low-ADBE',	'Low-ADI',	'Low-ADM',	'Low-ADP',	'Low-ADSK',	'Low-AEE',	'Low-AEP',	'Low-AES',	'Low-AFL',	'Low-AIG',	'Low-AIV',	'Low-AIZ',	'Low-AJG',	'Low-AKAM',	'Low-ALB',	'Low-ALGN',	'Low-ALK',	'Low-ALL',	'Low-ALLE',	'Low-ALXN',	'Low-AMAT',	'Low-AMCR',	'Low-AMD',	'Low-AME',	'Low-AMGN',	'Low-AMP',	'Low-AMT',	'Low-AMZN',	'Low-ANET',	'Low-ANSS',	'Low-ANTM',	'Low-AON',	'Low-AOS',	'Low-APA',	'Low-APD',	'Low-APH',	'Low-APTV',	'Low-ARE',	'Low-ATO',	'Low-ATVI',	'Low-AVB',	'Low-AVGO',	'Low-AVY',	'Low-AWK',	'Low-AXP',	'Low-AZO',	'Low-BA',	'Low-BAC',	'Low-BAX',	'Low-BBY',	'Low-BEN',	'Low-BIIB',	'Low-BK',	'Low-BKNG',	'Low-BKR',	'Low-BLL',	'Low-BMY',	'Low-BSX',	'Low-BWA',	'Low-BXP',	'Low-C',	'Low-CAG',	'Low-CAH',	'Low-CARR',	'Low-CAT',	'Low-CCI',	'Low-CCL',	'Low-CDNS',	'Low-CE',	'Low-CERN',	'Low-CF',	'Low-CFG',	'Low-CHD',	'Low-CHRW',	'Low-CHTR',	'Low-CI',	'Low-CINF',	'Low-CL',	'Low-CLX',	'Low-CMCSA',	'Low-CMG',	'Low-CMI',	'Low-CMS',	'Low-CNP',	'Low-COF',	'Low-COG',	'Low-COO',	'Low-COP',	'Low-COST',	'Low-COTY',	'Low-CPB',	'Low-CPRT',	'Low-CSX',	'Low-CTAS',	'Low-CTL',	'Low-CTSH',	'Low-CTVA',	'Low-CTXS',	'Low-CVX',	'Low-CXO',	'Low-D',	'Low-DAL',	'Low-DD',	'Low-DE',	'Low-DFS',	'Low-DHI',	'Low-DHR',	'Low-DIS',	'Low-DISCA',	'Low-DISCK',	'Low-DISH',	'Low-DLTR',	'Low-DOV',	'Low-DOW',	'Low-DPZ',	'Low-DRE',	'Low-DRI',	'Low-DTE',	'Low-DUK',	'Low-DVA',	'Low-DVN',	'Low-DXC',	'Low-DXCM',	'Low-EA',	'Low-EBAY',	'Low-ECL',	'Low-ED',	'Low-EFX',	'Low-EIX',	'Low-EL',	'Low-EMN',	'Low-EMR',	'Low-EQR',	'Low-ES',	'Low-ESS',	'Low-ETFC',	'Low-ETN',	'Low-ETR',	'Low-EW',	'Low-EXC',	'Low-EXPE',	'Low-EXR',	'Low-F',	'Low-FANG',	'Low-FAST',	'Low-FB',	'Low-FDX',	'Low-FFIV',	'Low-FIS',	'Low-FISV',	'Low-FITB',	'Low-FLS',	'Low-FMC',	'Low-FOX',	'Low-FOXA',	'Low-FRC',	'Low-FRT',	'Low-FTNT',	'Low-FTV',	'Low-GE',	'Low-GILD',	'Low-GIS',	'Low-GL',	'Low-GLW',	'Low-GM',	'Low-GOOG',	'Low-GPC',	'Low-GPN',	'Low-GRMN',	'Low-GS',	'Low-GWW',	'Low-HAL',	'Low-HBAN',	'Low-HBI',	'Low-HCA',	'Low-HES',	'Low-HFC',	'Low-HIG',	'Low-HLT',	'Low-HOLX',	'Low-HPE',	'Low-HPQ',	'Low-HRB',	'Low-HRL',	'Low-HSIC',	'Low-HST',	'Low-HSY',	'Low-HUM',	'Low-HWM',	'Low-IDXX',	'Low-IEX',	'Low-ILMN',	'Low-INCY',	'Low-INFO',	'Low-INTC',	'Low-INTU',	'Low-IP',	'Low-IPG',	'Low-IQV',	'Low-IR',	'Low-IRM',	'Low-IT',	'Low-ITW',	'Low-J',	'Low-JCI',	'Low-JNJ',	'Low-JNPR',	'Low-JPM',	'Low-KEY',	'Low-KHC',	'Low-KIM',	'Low-KLAC',	'Low-KMB',	'Low-KMX',	'Low-KO',	'Low-KSS',	'Low-L',	'Low-LB',	'Low-LDOS',	'Low-LEG',	'Low-LEN',	'Low-LH',	'Low-LIN',	'Low-LLY',	'Low-LMT',	'Low-LNC',	'Low-LNT',	'Low-LOW',	'Low-LRCX',	'Low-LUV',	'Low-LVS',	'Low-LW',	'Low-LYB',	'Low-LYV',	'Low-MA',	'Low-MAR',	'Low-MAS',	'Low-MCD',	'Low-MCHP',	'Low-MCK',	'Low-MCO',	'Low-MDT',	'Low-MGM',	'Low-MKC',	'Low-MKTX',	'Low-MLM',	'Low-MMM',	'Low-MNST',	'Low-MO',	'Low-MOS',	'Low-MPC',	'Low-MRK',	'Low-MRO',	'Low-MSCI',	'Low-MSFT',	'Low-MSI',	'Low-MTB',	'Low-MTD',	'Low-MU',	'Low-MXIM',	'Low-MYL',	'Low-NCLH',	'Low-NI',	'Low-NKE',	'Low-NLOK',	'Low-NOW',	'Low-NRG',	'Low-NSC',	'Low-NTAP',	'Low-NTRS',	'Low-NUE',	'Low-NWL',	'Low-NWS',	'Low-NWSA',	'Low-O',	'Low-OKE',	'Low-ORCL',	'Low-ORLY',	'Low-OTIS',	'Low-OXY',	'Low-PAYX',	'Low-PBCT',	'Low-PEAK',	'Low-PEG',	'Low-PEP',	'Low-PFE',	'Low-PFG',	'Low-PGR',	'Low-PH',	'Low-PHM',	'Low-PLD',	'Low-PM',	'Low-PNR',	'Low-PNW',	'Low-PRU',	'Low-PSA',	'Low-PSX',	'Low-PVH',	'Low-PWR',	'Low-PXD',	'Low-QCOM',	'Low-QRVO',	'Low-RCL',	'Low-RE',	'Low-REG',	'Low-REGN',	'Low-RF',	'Low-RHI',	'Low-RJF',	'Low-RL',	'Low-RMD',	'Low-ROK',	'Low-ROL',	'Low-ROP',	'Low-ROST',	'Low-SBUX',	'Low-SCHW',	'Low-SHW',	'Low-SJM',	'Low-SLB',	'Low-SNA',	'Low-SNPS',	'Low-SO',	'Low-SPGI',	'Low-SRE',	'Low-STE',	'Low-STT',	'Low-STZ',	'Low-SWK',	'Low-SWKS',	'Low-SYK',	'Low-SYY',	'Low-T',	'Low-TFC',	'Low-TFX',	'Low-TGT',	'Low-TIF',	'Low-TJX',	'Low-TMUS',	'Low-TPR',	'Low-TROW',	'Low-TRV',	'Low-TSCO',	'Low-TSN',	'Low-TT',	'Low-TTWO',	'Low-TWTR',	'Low-TXN',	'Low-TYL',	'Low-UA',	'Low-UAA',	'Low-UAL',	'Low-UHS',	'Low-ULTA',	'Low-UNM',	'Low-UNP',	'Low-UPS',	'Low-URI',	'Low-USB',	'Low-V',	'Low-VAR',	'Low-VFC',	'Low-VLO',	'Low-VMC',	'Low-VNO',	'Low-VRSK',	'Low-VRSN',	'Low-VRTX',	'Low-VTR',	'Low-WAB',	'Low-WAT',	'Low-WBA',	'Low-WDC',	'Low-WFC',	'Low-WHR',	'Low-WMT',	'Low-WRK',	'Low-WST',	'Low-WY',	'Low-XEL',	'Low-XLNX',	'Low-XOM',	'Low-XRAY',	'Low-XYL',	'Low-YUM',	'Low-ZBH',	'Low-ZBRA',	'Low-ZION',	'Low-ZTS',	'Low-BDX',	'Low-BF.B',	'Low-BIO',	'Low-BLK',	'Low-BR',	'Low-BRK.B',	'Low-CB',	'Low-CBOE',	'Low-CBRE',	'Low-CDW',	'Low-CMA',	'Low-CME',	'Low-CNC',	'Low-CRM',	'Low-CSCO',	'Low-CVS',	'Low-DG',	'Low-DGX',	'Low-DLR',	'Low-EOG',	'Low-EQIX',	'Low-EVRG',	'Low-EXPD',	'Low-FBHS',	'Low-FCX',	'Low-FE',	'Low-FLIR',	'Low-FLT',	'Low-FTI',	'Low-GD',	'Low-GOOGL',	'Low-GPS',	'Low-HAS',	'Low-HD',	'Low-HII',	'Low-HON',	'Low-IBM',	'Low-ICE',	'Low-IFF',	'Low-IPGP',	'Low-ISRG',	'Low-IVZ',	'Low-JBHT',	'Low-JKHY',	'Low-K',	'Low-KEYS',	'Low-KMI',	'Low-KR',	'Low-KSU',	'Low-LHX',	'Low-LKQ',	'Low-MAA',	'Low-MDLZ',	'Low-MET',	'Low-MHK',	'Low-MMC',	'Low-MS',	'Low-NBL',	'Low-NDAQ',	'Low-NEE',	'Low-NEM',	'Low-NFLX',	'Low-NLSN',	'Low-NOC',	'Low-NOV',	'Low-NVDA',	'Low-NVR',	'Low-ODFL',	'Low-OMC',	'Low-PAYC',	'Low-PCAR',	'Low-PG',	'Low-PKG',	'Low-PKI',	'Low-PNC',	'Low-PPG',	'Low-PPL',	'Low-PRGO',	'Low-PYPL',	'Low-RSG',	'Low-RTX',	'Low-SBAC',	'Low-SEE',	'Low-SIVB',	'Low-SLG',	'Low-SPG',	'Low-STX',	'Low-SYF',	'Low-TAP',	'Low-TDG',	'Low-TDY',	'Low-TEL',	'Low-TMO',	'Low-TXT',	'Low-UDR',	'Low-UNH',	'Low-VIAC',	'Low-VZ',	'Low-WEC',	'Low-WELL',	'Low-WLTW',	'Low-WM',	'Low-WMB',	'Low-WRB',	'Low-WU',	'Low-WYNN',	'Low-XRX']
low_df = df1[lowslice_list]
low_df.head()

,Date,Low-Attributes,Low-A,Low-AAL,Low-AAP,Low-AAPL,Low-ABBV,Low-ABC,Low-ABMD,Low-ABT,...,Low-VZ,Low-WEC,Low-WELL,Low-WLTW,Low-WM,Low-WMB,Low-WRB,Low-WU,Low-WYNN,Low-XRX
0,1/2/2020,Low,85.199997,28.650000,157.529999,295.190002,88.510002,84.339996,167.139999,85.800003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/3/2020,Low,84.500000,27.340000,157.250000,296.500000,87.900002,83.269997,165.240005,85.589996,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/6/2020,Low,83.599998,27.080000,156.429993,292.750000,87.980003,83.010002,166.020004,85.209999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/7/2020,Low,83.940002,27.059999,152.410004,297.480011,88.260002,84.190002,177.190002,85.540001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/8/2020,Low,85.199997,27.070000,153.139999,297.160004,88.870003,84.529999,174.289993,85.930000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
low_df.dropna(axis=1, how='all', inplace=True)
low_df.fillna(0)
low_df.columns = low_df.columns.str.replace('Low-','')
low_df.head()

<ipython-input-21-cdf5645e1346>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  low_df.dropna(axis=1, how='all', inplace=True)

,Date,Attributes,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
0,1/2/2020,Low,85.199997,28.650000,157.529999,295.190002,88.510002,84.339996,167.139999,85.800003,...,62.200001,98.779999,70.239998,56.130001,78.760002,100.809998,147.470001,255.169998,51.790001,131.479996
1,1/3/2020,Low,84.500000,27.340000,157.250000,296.500000,87.900002,83.269997,165.240005,85.589996,...,62.279999,99.099998,70.160004,55.849998,78.699997,100.360001,145.960007,254.880005,51.160000,132.270004
2,1/6/2020,Low,83.599998,27.080000,156.429993,292.750000,87.980003,83.010002,166.020004,85.209999,...,62.330002,96.900002,70.230003,56.009998,78.910004,101.059998,147.229996,252.619995,50.810001,132.710007
3,1/7/2020,Low,83.940002,27.059999,152.410004,297.480011,88.260002,84.190002,177.190002,85.540001,...,61.970001,97.440002,69.510002,56.290001,79.019997,101.540001,146.690002,256.079987,50.610001,132.669998
4,1/8/2020,Low,85.199997,27.070000,153.139999,297.160004,88.870003,84.529999,174.289993,85.930000,...,62.119999,98.510002,69.169998,57.070000,79.190002,100.339996,147.440002,247.250000,50.730000,133.240005

In [22]:
low_df.to_csv('yahoo_low_df.csv')

In [23]:
openslice_list = ['Date',	'Open-Attributes',	'Open-A',	'Open-AAL',	'Open-AAP',	'Open-AAPL',	'Open-ABBV',	'Open-ABC',	'Open-ABMD',	'Open-ABT',	'Open-ACN',	'Open-ADBE',	'Open-ADI',	'Open-ADM',	'Open-ADP',	'Open-ADSK',	'Open-AEE',	'Open-AEP',	'Open-AES',	'Open-AFL',	'Open-AIG',	'Open-AIV',	'Open-AIZ',	'Open-AJG',	'Open-AKAM',	'Open-ALB',	'Open-ALGN',	'Open-ALK',	'Open-ALL',	'Open-ALLE',	'Open-ALXN',	'Open-AMAT',	'Open-AMCR',	'Open-AMD',	'Open-AME',	'Open-AMGN',	'Open-AMP',	'Open-AMT',	'Open-AMZN',	'Open-ANET',	'Open-ANSS',	'Open-ANTM',	'Open-AON',	'Open-AOS',	'Open-APA',	'Open-APD',	'Open-APH',	'Open-APTV',	'Open-ARE',	'Open-ATO',	'Open-ATVI',	'Open-AVB',	'Open-AVGO',	'Open-AVY',	'Open-AWK',	'Open-AXP',	'Open-AZO',	'Open-BA',	'Open-BAC',	'Open-BAX',	'Open-BBY',	'Open-BEN',	'Open-BIIB',	'Open-BK',	'Open-BKNG',	'Open-BKR',	'Open-BLL',	'Open-BMY',	'Open-BSX',	'Open-BWA',	'Open-BXP',	'Open-C',	'Open-CAG',	'Open-CAH',	'Open-CARR',	'Open-CAT',	'Open-CCI',	'Open-CCL',	'Open-CDNS',	'Open-CE',	'Open-CERN',	'Open-CF',	'Open-CFG',	'Open-CHD',	'Open-CHRW',	'Open-CHTR',	'Open-CI',	'Open-CINF',	'Open-CL',	'Open-CLX',	'Open-CMCSA',	'Open-CMG',	'Open-CMI',	'Open-CMS',	'Open-CNP',	'Open-COF',	'Open-COG',	'Open-COO',	'Open-COP',	'Open-COST',	'Open-COTY',	'Open-CPB',	'Open-CPRT',	'Open-CSX',	'Open-CTAS',	'Open-CTL',	'Open-CTSH',	'Open-CTVA',	'Open-CTXS',	'Open-CVX',	'Open-CXO',	'Open-D',	'Open-DAL',	'Open-DD',	'Open-DE',	'Open-DFS',	'Open-DHI',	'Open-DHR',	'Open-DIS',	'Open-DISCA',	'Open-DISCK',	'Open-DISH',	'Open-DLTR',	'Open-DOV',	'Open-DOW',	'Open-DPZ',	'Open-DRE',	'Open-DRI',	'Open-DTE',	'Open-DUK',	'Open-DVA',	'Open-DVN',	'Open-DXC',	'Open-DXCM',	'Open-EA',	'Open-EBAY',	'Open-ECL',	'Open-ED',	'Open-EFX',	'Open-EIX',	'Open-EL',	'Open-EMN',	'Open-EMR',	'Open-EQR',	'Open-ES',	'Open-ESS',	'Open-ETFC',	'Open-ETN',	'Open-ETR',	'Open-EW',	'Open-EXC',	'Open-EXPE',	'Open-EXR',	'Open-F',	'Open-FANG',	'Open-FAST',	'Open-FB',	'Open-FDX',	'Open-FFIV',	'Open-FIS',	'Open-FISV',	'Open-FITB',	'Open-FLS',	'Open-FMC',	'Open-FOX',	'Open-FOXA',	'Open-FRC',	'Open-FRT',	'Open-FTNT',	'Open-FTV',	'Open-GE',	'Open-GILD',	'Open-GIS',	'Open-GL',	'Open-GLW',	'Open-GM',	'Open-GOOG',	'Open-GPC',	'Open-GPN',	'Open-GRMN',	'Open-GS',	'Open-GWW',	'Open-HAL',	'Open-HBAN',	'Open-HBI',	'Open-HCA',	'Open-HES',	'Open-HFC',	'Open-HIG',	'Open-HLT',	'Open-HOLX',	'Open-HPE',	'Open-HPQ',	'Open-HRB',	'Open-HRL',	'Open-HSIC',	'Open-HST',	'Open-HSY',	'Open-HUM',	'Open-HWM',	'Open-IDXX',	'Open-IEX',	'Open-ILMN',	'Open-INCY',	'Open-INFO',	'Open-INTC',	'Open-INTU',	'Open-IP',	'Open-IPG',	'Open-IQV',	'Open-IR',	'Open-IRM',	'Open-IT',	'Open-ITW',	'Open-J',	'Open-JCI',	'Open-JNJ',	'Open-JNPR',	'Open-JPM',	'Open-KEY',	'Open-KHC',	'Open-KIM',	'Open-KLAC',	'Open-KMB',	'Open-KMX',	'Open-KO',	'Open-KSS',	'Open-L',	'Open-LB',	'Open-LDOS',	'Open-LEG',	'Open-LEN',	'Open-LH',	'Open-LIN',	'Open-LLY',	'Open-LMT',	'Open-LNC',	'Open-LNT',	'Open-LOW',	'Open-LRCX',	'Open-LUV',	'Open-LVS',	'Open-LW',	'Open-LYB',	'Open-LYV',	'Open-MA',	'Open-MAR',	'Open-MAS',	'Open-MCD',	'Open-MCHP',	'Open-MCK',	'Open-MCO',	'Open-MDT',	'Open-MGM',	'Open-MKC',	'Open-MKTX',	'Open-MLM',	'Open-MMM',	'Open-MNST',	'Open-MO',	'Open-MOS',	'Open-MPC',	'Open-MRK',	'Open-MRO',	'Open-MSCI',	'Open-MSFT',	'Open-MSI',	'Open-MTB',	'Open-MTD',	'Open-MU',	'Open-MXIM',	'Open-MYL',	'Open-NCLH',	'Open-NI',	'Open-NKE',	'Open-NLOK',	'Open-NOW',	'Open-NRG',	'Open-NSC',	'Open-NTAP',	'Open-NTRS',	'Open-NUE',	'Open-NWL',	'Open-NWS',	'Open-NWSA',	'Open-O',	'Open-OKE',	'Open-ORCL',	'Open-ORLY',	'Open-OTIS',	'Open-OXY',	'Open-PAYX',	'Open-PBCT',	'Open-PEAK',	'Open-PEG',	'Open-PEP',	'Open-PFE',	'Open-PFG',	'Open-PGR',	'Open-PH',	'Open-PHM',	'Open-PLD',	'Open-PM',	'Open-PNR',	'Open-PNW',	'Open-PRU',	'Open-PSA',	'Open-PSX',	'Open-PVH',	'Open-PWR',	'Open-PXD',	'Open-QCOM',	'Open-QRVO',	'Open-RCL',	'Open-RE',	'Open-REG',	'Open-REGN',	'Open-RF',	'Open-RHI',	'Open-RJF',	'Open-RL',	'Open-RMD',	'Open-ROK',	'Open-ROL',	'Open-ROP',	'Open-ROST',	'Open-SBUX',	'Open-SCHW',	'Open-SHW',	'Open-SJM',	'Open-SLB',	'Open-SNA',	'Open-SNPS',	'Open-SO',	'Open-SPGI',	'Open-SRE',	'Open-STE',	'Open-STT',	'Open-STZ',	'Open-SWK',	'Open-SWKS',	'Open-SYK',	'Open-SYY',	'Open-T',	'Open-TFC',	'Open-TFX',	'Open-TGT',	'Open-TIF',	'Open-TJX',	'Open-TMUS',	'Open-TPR',	'Open-TROW',	'Open-TRV',	'Open-TSCO',	'Open-TSN',	'Open-TT',	'Open-TTWO',	'Open-TWTR',	'Open-TXN',	'Open-TYL',	'Open-UA',	'Open-UAA',	'Open-UAL',	'Open-UHS',	'Open-ULTA',	'Open-UNM',	'Open-UNP',	'Open-UPS',	'Open-URI',	'Open-USB',	'Open-V',	'Open-VAR',	'Open-VFC',	'Open-VLO',	'Open-VMC',	'Open-VNO',	'Open-VRSK',	'Open-VRSN',	'Open-VRTX',	'Open-VTR',	'Open-WAB',	'Open-WAT',	'Open-WBA',	'Open-WDC',	'Open-WFC',	'Open-WHR',	'Open-WMT',	'Open-WRK',	'Open-WST',	'Open-WY',	'Open-XEL',	'Open-XLNX',	'Open-XOM',	'Open-XRAY',	'Open-XYL',	'Open-YUM',	'Open-ZBH',	'Open-ZBRA',	'Open-ZION',	'Open-ZTS',	'Open-BDX',	'Open-BF.B',	'Open-BIO',	'Open-BLK',	'Open-BR',	'Open-BRK.B',	'Open-CB',	'Open-CBOE',	'Open-CBRE',	'Open-CDW',	'Open-CMA',	'Open-CME',	'Open-CNC',	'Open-CRM',	'Open-CSCO',	'Open-CVS',	'Open-DG',	'Open-DGX',	'Open-DLR',	'Open-EOG',	'Open-EQIX',	'Open-EVRG',	'Open-EXPD',	'Open-FBHS',	'Open-FCX',	'Open-FE',	'Open-FLIR',	'Open-FLT',	'Open-FTI',	'Open-GD',	'Open-GOOGL',	'Open-GPS',	'Open-HAS',	'Open-HD',	'Open-HII',	'Open-HON',	'Open-IBM',	'Open-ICE',	'Open-IFF',	'Open-IPGP',	'Open-ISRG',	'Open-IVZ',	'Open-JBHT',	'Open-JKHY',	'Open-K',	'Open-KEYS',	'Open-KMI',	'Open-KR',	'Open-KSU',	'Open-LHX',	'Open-LKQ',	'Open-MAA',	'Open-MDLZ',	'Open-MET',	'Open-MHK',	'Open-MMC',	'Open-MS',	'Open-NBL',	'Open-NDAQ',	'Open-NEE',	'Open-NEM',	'Open-NFLX',	'Open-NLSN',	'Open-NOC',	'Open-NOV',	'Open-NVDA',	'Open-NVR',	'Open-ODFL',	'Open-OMC',	'Open-PAYC',	'Open-PCAR',	'Open-PG',	'Open-PKG',	'Open-PKI',	'Open-PNC',	'Open-PPG',	'Open-PPL',	'Open-PRGO',	'Open-PYPL',	'Open-RSG',	'Open-RTX',	'Open-SBAC',	'Open-SEE',	'Open-SIVB',	'Open-SLG',	'Open-SPG',	'Open-STX',	'Open-SYF',	'Open-TAP',	'Open-TDG',	'Open-TDY',	'Open-TEL',	'Open-TMO',	'Open-TXT',	'Open-UDR',	'Open-UNH',	'Open-VIAC',	'Open-VZ',	'Open-WEC',	'Open-WELL',	'Open-WLTW',	'Open-WM',	'Open-WMB',	'Open-WRB',	'Open-WU',	'Open-WYNN',	'Open-XRX']
open_df = df1[openslice_list]
open_df.head()

,Date,Open-Attributes,Open-A,Open-AAL,Open-AAP,Open-AAPL,Open-ABBV,Open-ABC,Open-ABMD,Open-ABT,...,Open-VZ,Open-WEC,Open-WELL,Open-WLTW,Open-WM,Open-WMB,Open-WRB,Open-WU,Open-WYNN,Open-XRX
0,1/2/2020,Open,85.900002,28.980000,160.470001,296.239990,89.080002,85.639999,172.509995,86.059998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/3/2020,Open,84.669998,28.270000,158.029999,297.149994,88.169998,83.809998,166.830002,85.750000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/6/2020,Open,84.000000,27.190001,157.740005,293.790008,88.220001,83.680000,166.529999,85.620003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/7/2020,Open,83.959999,27.559999,156.899994,299.839996,88.930000,84.760002,178.830002,85.769997,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/8/2020,Open,85.959999,27.100000,154.850006,297.160004,89.150002,84.559998,178.380005,86.239998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
open_df.dropna(axis=1, how='all', inplace=True)
open_df.fillna(0)
open_df.columns = open_df.columns.str.replace('Open-','')
open_df.head()

<ipython-input-24-f7e0fbbf7f18>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  open_df.dropna(axis=1, how='all', inplace=True)

,Date,Attributes,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
0,1/2/2020,Open,85.900002,28.980000,160.470001,296.239990,89.080002,85.639999,172.509995,86.059998,...,63.549999,99.150002,70.239998,56.830002,79.160004,100.900002,149.979996,259.029999,52.360001,132.050003
1,1/3/2020,Open,84.669998,28.270000,158.029999,297.149994,88.169998,83.809998,166.830002,85.750000,...,62.279999,100.550003,71.339996,56.240002,79.029999,101.419998,147.419998,256.100006,51.410000,132.479996
2,1/6/2020,Open,84.000000,27.190001,157.740005,293.790008,88.220001,83.680000,166.529999,85.620003,...,62.759998,97.839996,70.320000,56.040001,79.860001,101.430000,148.570007,252.619995,51.080002,133.779999
3,1/7/2020,Open,83.959999,27.559999,156.899994,299.839996,88.930000,84.760002,178.830002,85.769997,...,62.150002,98.220001,70.500000,56.349998,79.910004,101.750000,148.550003,257.500000,50.790001,133.000000
4,1/8/2020,Open,85.959999,27.100000,154.850006,297.160004,89.150002,84.559998,178.380005,86.239998,...,62.590000,99.360001,70.110001,57.150002,79.660004,100.470001,148.350006,251.279999,50.900002,133.759995

In [25]:
open_df.to_csv('yahoo_open_df.csv')

In [26]:
volumeslice_list = ['Date',	'Volume-Attributes',	'Volume-A',	'Volume-AAL',	'Volume-AAP',	'Volume-AAPL',	'Volume-ABBV',	'Volume-ABC',	'Volume-ABMD',	'Volume-ABT',	'Volume-ACN',	'Volume-ADBE',	'Volume-ADI',	'Volume-ADM',	'Volume-ADP',	'Volume-ADSK',	'Volume-AEE',	'Volume-AEP',	'Volume-AES',	'Volume-AFL',	'Volume-AIG',	'Volume-AIV',	'Volume-AIZ',	'Volume-AJG',	'Volume-AKAM',	'Volume-ALB',	'Volume-ALGN',	'Volume-ALK',	'Volume-ALL',	'Volume-ALLE',	'Volume-ALXN',	'Volume-AMAT',	'Volume-AMCR',	'Volume-AMD',	'Volume-AME',	'Volume-AMGN',	'Volume-AMP',	'Volume-AMT',	'Volume-AMZN',	'Volume-ANET',	'Volume-ANSS',	'Volume-ANTM',	'Volume-AON',	'Volume-AOS',	'Volume-APA',	'Volume-APD',	'Volume-APH',	'Volume-APTV',	'Volume-ARE',	'Volume-ATO',	'Volume-ATVI',	'Volume-AVB',	'Volume-AVGO',	'Volume-AVY',	'Volume-AWK',	'Volume-AXP',	'Volume-AZO',	'Volume-BA',	'Volume-BAC',	'Volume-BAX',	'Volume-BBY',	'Volume-BEN',	'Volume-BIIB',	'Volume-BK',	'Volume-BKNG',	'Volume-BKR',	'Volume-BLL',	'Volume-BMY',	'Volume-BSX',	'Volume-BWA',	'Volume-BXP',	'Volume-C',	'Volume-CAG',	'Volume-CAH',	'Volume-CARR',	'Volume-CAT',	'Volume-CCI',	'Volume-CCL',	'Volume-CDNS',	'Volume-CE',	'Volume-CERN',	'Volume-CF',	'Volume-CFG',	'Volume-CHD',	'Volume-CHRW',	'Volume-CHTR',	'Volume-CI',	'Volume-CINF',	'Volume-CL',	'Volume-CLX',	'Volume-CMCSA',	'Volume-CMG',	'Volume-CMI',	'Volume-CMS',	'Volume-CNP',	'Volume-COF',	'Volume-COG',	'Volume-COO',	'Volume-COP',	'Volume-COST',	'Volume-COTY',	'Volume-CPB',	'Volume-CPRT',	'Volume-CSX',	'Volume-CTAS',	'Volume-CTL',	'Volume-CTSH',	'Volume-CTVA',	'Volume-CTXS',	'Volume-CVX',	'Volume-CXO',	'Volume-D',	'Volume-DAL',	'Volume-DD',	'Volume-DE',	'Volume-DFS',	'Volume-DHI',	'Volume-DHR',	'Volume-DIS',	'Volume-DISCA',	'Volume-DISCK',	'Volume-DISH',	'Volume-DLTR',	'Volume-DOV',	'Volume-DOW',	'Volume-DPZ',	'Volume-DRE',	'Volume-DRI',	'Volume-DTE',	'Volume-DUK',	'Volume-DVA',	'Volume-DVN',	'Volume-DXC',	'Volume-DXCM',	'Volume-EA',	'Volume-EBAY',	'Volume-ECL',	'Volume-ED',	'Volume-EFX',	'Volume-EIX',	'Volume-EL',	'Volume-EMN',	'Volume-EMR',	'Volume-EQR',	'Volume-ES',	'Volume-ESS',	'Volume-ETFC',	'Volume-ETN',	'Volume-ETR',	'Volume-EW',	'Volume-EXC',	'Volume-EXPE',	'Volume-EXR',	'Volume-F',	'Volume-FANG',	'Volume-FAST',	'Volume-FB',	'Volume-FDX',	'Volume-FFIV',	'Volume-FIS',	'Volume-FISV',	'Volume-FITB',	'Volume-FLS',	'Volume-FMC',	'Volume-FOX',	'Volume-FOXA',	'Volume-FRC',	'Volume-FRT',	'Volume-FTNT',	'Volume-FTV',	'Volume-GE',	'Volume-GILD',	'Volume-GIS',	'Volume-GL',	'Volume-GLW',	'Volume-GM',	'Volume-GOOG',	'Volume-GPC',	'Volume-GPN',	'Volume-GRMN',	'Volume-GS',	'Volume-GWW',	'Volume-HAL',	'Volume-HBAN',	'Volume-HBI',	'Volume-HCA',	'Volume-HES',	'Volume-HFC',	'Volume-HIG',	'Volume-HLT',	'Volume-HOLX',	'Volume-HPE',	'Volume-HPQ',	'Volume-HRB',	'Volume-HRL',	'Volume-HSIC',	'Volume-HST',	'Volume-HSY',	'Volume-HUM',	'Volume-HWM',	'Volume-IDXX',	'Volume-IEX',	'Volume-ILMN',	'Volume-INCY',	'Volume-INFO',	'Volume-INTC',	'Volume-INTU',	'Volume-IP',	'Volume-IPG',	'Volume-IQV',	'Volume-IR',	'Volume-IRM',	'Volume-IT',	'Volume-ITW',	'Volume-J',	'Volume-JCI',	'Volume-JNJ',	'Volume-JNPR',	'Volume-JPM',	'Volume-KEY',	'Volume-KHC',	'Volume-KIM',	'Volume-KLAC',	'Volume-KMB',	'Volume-KMX',	'Volume-KO',	'Volume-KSS',	'Volume-L',	'Volume-LB',	'Volume-LDOS',	'Volume-LEG',	'Volume-LEN',	'Volume-LH',	'Volume-LIN',	'Volume-LLY',	'Volume-LMT',	'Volume-LNC',	'Volume-LNT',	'Volume-LOW',	'Volume-LRCX',	'Volume-LUV',	'Volume-LVS',	'Volume-LW',	'Volume-LYB',	'Volume-LYV',	'Volume-MA',	'Volume-MAR',	'Volume-MAS',	'Volume-MCD',	'Volume-MCHP',	'Volume-MCK',	'Volume-MCO',	'Volume-MDT',	'Volume-MGM',	'Volume-MKC',	'Volume-MKTX',	'Volume-MLM',	'Volume-MMM',	'Volume-MNST',	'Volume-MO',	'Volume-MOS',	'Volume-MPC',	'Volume-MRK',	'Volume-MRO',	'Volume-MSCI',	'Volume-MSFT',	'Volume-MSI',	'Volume-MTB',	'Volume-MTD',	'Volume-MU',	'Volume-MXIM',	'Volume-MYL',	'Volume-NCLH',	'Volume-NI',	'Volume-NKE',	'Volume-NLOK',	'Volume-NOW',	'Volume-NRG',	'Volume-NSC',	'Volume-NTAP',	'Volume-NTRS',	'Volume-NUE',	'Volume-NWL',	'Volume-NWS',	'Volume-NWSA',	'Volume-O',	'Volume-OKE',	'Volume-ORCL',	'Volume-ORLY',	'Volume-OTIS',	'Volume-OXY',	'Volume-PAYX',	'Volume-PBCT',	'Volume-PEAK',	'Volume-PEG',	'Volume-PEP',	'Volume-PFE',	'Volume-PFG',	'Volume-PGR',	'Volume-PH',	'Volume-PHM',	'Volume-PLD',	'Volume-PM',	'Volume-PNR',	'Volume-PNW',	'Volume-PRU',	'Volume-PSA',	'Volume-PSX',	'Volume-PVH',	'Volume-PWR',	'Volume-PXD',	'Volume-QCOM',	'Volume-QRVO',	'Volume-RCL',	'Volume-RE',	'Volume-REG',	'Volume-REGN',	'Volume-RF',	'Volume-RHI',	'Volume-RJF',	'Volume-RL',	'Volume-RMD',	'Volume-ROK',	'Volume-ROL',	'Volume-ROP',	'Volume-ROST',	'Volume-SBUX',	'Volume-SCHW',	'Volume-SHW',	'Volume-SJM',	'Volume-SLB',	'Volume-SNA',	'Volume-SNPS',	'Volume-SO',	'Volume-SPGI',	'Volume-SRE',	'Volume-STE',	'Volume-STT',	'Volume-STZ',	'Volume-SWK',	'Volume-SWKS',	'Volume-SYK',	'Volume-SYY',	'Volume-T',	'Volume-TFC',	'Volume-TFX',	'Volume-TGT',	'Volume-TIF',	'Volume-TJX',	'Volume-TMUS',	'Volume-TPR',	'Volume-TROW',	'Volume-TRV',	'Volume-TSCO',	'Volume-TSN',	'Volume-TT',	'Volume-TTWO',	'Volume-TWTR',	'Volume-TXN',	'Volume-TYL',	'Volume-UA',	'Volume-UAA',	'Volume-UAL',	'Volume-UHS',	'Volume-ULTA',	'Volume-UNM',	'Volume-UNP',	'Volume-UPS',	'Volume-URI',	'Volume-USB',	'Volume-V',	'Volume-VAR',	'Volume-VFC',	'Volume-VLO',	'Volume-VMC',	'Volume-VNO',	'Volume-VRSK',	'Volume-VRSN',	'Volume-VRTX',	'Volume-VTR',	'Volume-WAB',	'Volume-WAT',	'Volume-WBA',	'Volume-WDC',	'Volume-WFC',	'Volume-WHR',	'Volume-WMT',	'Volume-WRK',	'Volume-WST',	'Volume-WY',	'Volume-XEL',	'Volume-XLNX',	'Volume-XOM',	'Volume-XRAY',	'Volume-XYL',	'Volume-YUM',	'Volume-ZBH',	'Volume-ZBRA',	'Volume-ZION',	'Volume-ZTS',	'Volume-BDX',	'Volume-BF.B',	'Volume-BIO',	'Volume-BLK',	'Volume-BR',	'Volume-BRK.B',	'Volume-CB',	'Volume-CBOE',	'Volume-CBRE',	'Volume-CDW',	'Volume-CMA',	'Volume-CME',	'Volume-CNC',	'Volume-CRM',	'Volume-CSCO',	'Volume-CVS',	'Volume-DG',	'Volume-DGX',	'Volume-DLR',	'Volume-EOG',	'Volume-EQIX',	'Volume-EVRG',	'Volume-EXPD',	'Volume-FBHS',	'Volume-FCX',	'Volume-FE',	'Volume-FLIR',	'Volume-FLT',	'Volume-FTI',	'Volume-GD',	'Volume-GOOGL',	'Volume-GPS',	'Volume-HAS',	'Volume-HD',	'Volume-HII',	'Volume-HON',	'Volume-IBM',	'Volume-ICE',	'Volume-IFF',	'Volume-IPGP',	'Volume-ISRG',	'Volume-IVZ',	'Volume-JBHT',	'Volume-JKHY',	'Volume-K',	'Volume-KEYS',	'Volume-KMI',	'Volume-KR',	'Volume-KSU',	'Volume-LHX',	'Volume-LKQ',	'Volume-MAA',	'Volume-MDLZ',	'Volume-MET',	'Volume-MHK',	'Volume-MMC',	'Volume-MS',	'Volume-NBL',	'Volume-NDAQ',	'Volume-NEE',	'Volume-NEM',	'Volume-NFLX',	'Volume-NLSN',	'Volume-NOC',	'Volume-NOV',	'Volume-NVDA',	'Volume-NVR',	'Volume-ODFL',	'Volume-OMC',	'Volume-PAYC',	'Volume-PCAR',	'Volume-PG',	'Volume-PKG',	'Volume-PKI',	'Volume-PNC',	'Volume-PPG',	'Volume-PPL',	'Volume-PRGO',	'Volume-PYPL',	'Volume-RSG',	'Volume-RTX',	'Volume-SBAC',	'Volume-SEE',	'Volume-SIVB',	'Volume-SLG',	'Volume-SPG',	'Volume-STX',	'Volume-SYF',	'Volume-TAP',	'Volume-TDG',	'Volume-TDY',	'Volume-TEL',	'Volume-TMO',	'Volume-TXT',	'Volume-UDR',	'Volume-UNH',	'Volume-VIAC',	'Volume-VZ',	'Volume-WEC',	'Volume-WELL',	'Volume-WLTW',	'Volume-WM',	'Volume-WMB',	'Volume-WRB',	'Volume-WU',	'Volume-WYNN',	'Volume-XRX']
volume_df = df1[volumeslice_list]
volume_df.head()

,Date,Volume-Attributes,Volume-A,Volume-AAL,Volume-AAP,Volume-AAPL,Volume-ABBV,Volume-ABC,Volume-ABMD,Volume-ABT,...,Volume-VZ,Volume-WEC,Volume-WELL,Volume-WLTW,Volume-WM,Volume-WMB,Volume-WRB,Volume-WU,Volume-WYNN,Volume-XRX
0,1/2/2020,Volume,1410500,6451100,944900,33870100,5639200,817600,742600,4969000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/3/2020,Volume,1118300,14008900,567000,36580700,5988500,801500,746100,4747000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/6/2020,Volume,1993200,6105800,880200,29596800,6786600,765000,1505700,5631700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/7/2020,Volume,1684700,6105900,1129500,27218000,7242500,845300,990800,3408100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/8/2020,Volume,1847600,10496800,825700,33019800,7696800,1182000,1122400,5693900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
volume_df.dropna(axis=1, how='all', inplace=True)
volume_df.fillna(0)
volume_df.columns = volume_df.columns.str.replace('Volume-','')
volume_df.head()

<ipython-input-27-e88b97f4ec5f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  volume_df.dropna(axis=1, how='all', inplace=True)

,Date,Attributes,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
0,1/2/2020,Volume,1410500,6451100,944900,33870100,5639200,817600,742600,4969000,...,2915400,3234100,12456400,1556600,869500,1369900,1052400,387800,1528700,1576700
1,1/3/2020,Volume,1118300,14008900,567000,36580700,5988500,801500,746100,4747000,...,2422500,3521900,17386900,910000,795100,1145500,963500,305300,1215800,1274000
2,1/6/2020,Volume,1993200,6105800,880200,29596800,6786600,765000,1505700,5631700,...,2217100,2832700,20081900,751000,817300,1454100,944100,322600,1217500,2334100
3,1/7/2020,Volume,1684700,6105900,1129500,27218000,7242500,845300,990800,3408100,...,1861100,3050000,17387700,792600,662200,1388600,907300,236300,1450900,1224500
4,1/8/2020,Volume,1847600,10496800,825700,33019800,7696800,1182000,1122400,5693900,...,4828900,2172900,15137700,1001500,1083200,1521500,908800,689600,2396000,1766700

In [28]:
volume_df.to_csv('yahoo_volume_df.csv')

In [29]:
frames = [adj_df, close_df, high_df, low_df, open_df, volume_df ]
Stocks_companies = pd.concat(frames)
Stocks_companies.head()

,Date,Attributes,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
0,1/2/2020,Adj Close,85.552170,28.982893,158.410934,298.292145,86.008141,84.283539,168.809998,85.885757,...,61.569065,100.765846,68.567070,56.634895,79.849998,101.184380,148.520401,259.140015,51.462421,133.542831
1,1/3/2020,Adj Close,84.178558,27.548195,158.420868,295.392120,85.191757,83.223557,166.820007,84.838737,...,61.865166,98.446198,68.015823,56.008160,80.320000,100.867470,148.132172,256.049988,50.736221,133.562759
2,1/6/2020,Adj Close,84.427406,27.219410,155.817291,297.745880,85.864067,84.442039,179.039993,85.283234,...,61.776337,96.394203,68.538055,56.316555,79.800003,100.808052,147.276093,258.010010,50.117962,132.537338
3,1/7/2020,Adj Close,84.686203,27.119778,153.968964,296.345581,85.374245,83.837746,180.350006,84.809113,...,61.648026,98.594894,67.977135,56.614998,79.500000,100.986313,147.146683,256.470001,49.813740,132.985321
4,1/8/2020,Adj Close,85.522316,27.737495,152.200104,301.112640,85.979324,84.650070,178.690002,85.154816,...,61.588806,98.317329,66.952019,57.211887,79.769997,101.164581,148.908630,247.639999,50.304417,132.696609

In [30]:
Stocks_companies.set_index('Date')
# Stocks_companies.Date = pd.to_datetime(Stocks_companies.Date.str[0])
# Stocks_companies.index = pd.to_datetime(Stocks_companies.index)

,Attributes,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
1/2/2020,Adj Close,8.555217e+01,2.898289e+01,1.584109e+02,2.982921e+02,8.600814e+01,84.283539,168.809998,8.588576e+01,2.076396e+02,...,6.156907e+01,1.007658e+02,6.856707e+01,5.663490e+01,7.985000e+01,1.011844e+02,1.485204e+02,259.140015,5.146242e+01,1.335428e+02
1/3/2020,Adj Close,8.417856e+01,2.754819e+01,1.584209e+02,2.953921e+02,8.519176e+01,83.223557,166.820007,8.483874e+01,2.072938e+02,...,6.186517e+01,9.844620e+01,6.801582e+01,5.600816e+01,8.032000e+01,1.008675e+02,1.481322e+02,256.049988,5.073622e+01,1.335628e+02
1/6/2020,Adj Close,8.442741e+01,2.721941e+01,1.558173e+02,2.977459e+02,8.586407e+01,84.442039,179.039993,8.528323e+01,2.059402e+02,...,6.177634e+01,9.639420e+01,6.853806e+01,5.631656e+01,7.980000e+01,1.008081e+02,1.472761e+02,258.010010,5.011796e+01,1.325373e+02
1/7/2020,Adj Close,8.468620e+01,2.711978e+01,1.539690e+02,2.963456e+02,8.537424e+01,83.837746,180.350006,8.480911e+01,2.014939e+02,...,6.164803e+01,9.859489e+01,6.797713e+01,5.661500e+01,7.950000e+01,1.009863e+02,1.471467e+02,256.470001,4.981374e+01,1.329853e+02
1/8/2020,Adj Close,8.552232e+01,2.773750e+01,1.522001e+02,3.011126e+02,8.597932e+01,84.650070,178.690002,8.515482e+01,2.018892e+02,...,6.158881e+01,9.831733e+01,6.695202e+01,5.721189e+01,7.977000e+01,1.011646e+02,1.489086e+02,247.639999,5.030442e+01,1.326966e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7/27/2020,Volume,1.177100e+06,6.945170e+07,7.713000e+05,3.030350e+07,5.030700e+06,564600.000000,261300.000000,3.717900e+06,1.523200e+06,...,1.941000e+06,2.945500e+06,1.854790e+07,1.009700e+06,9.358000e+05,2.213300e+06,9.639000e+05,347500.000000,1.470800e+06,1.256700e+06
7/28/2020,Volume,1.373700e+06,6.235660e+07,8.085000e+05,2.590640e+07,5.941800e+06,670200.000000,250200.000000,4.114200e+06,1.422300e+06,...,1.686400e+06,2.135900e+06,1.919050e+07,1.297800e+06,7.747000e+05,2.171100e+06,1.173100e+06,458300.000000,1.196500e+06,2.257500e+06
7/29/2020,Volume,1.125300e+06,5.221460e+07,1.249400e+06,2.258230e+07,5.512000e+06,623000.000000,299300.000000,4.744200e+06,1.473700e+06,...,1.741900e+06,2.514300e+06,1.414320e+07,9.830000e+05,1.196500e+06,2.777900e+06,1.111000e+06,404600.000000,1.866100e+06,1.059600e+06
7/30/2020,Volume,1.663300e+06,4.052510e+07,1.350800e+06,3.953250e+07,6.411500e+06,645700.000000,277300.000000,3.176900e+06,1.408600e+06,...,2.103000e+06,4.840800e+06,2.990110e+07,2.120200e+06,1.304800e+06,3.863100e+06,9.872000e+05,205700.000000,1.336000e+06,1.129300e+06
7/31/2020,Volume,1.551800e+06,5.183550e+07,8.290000e+05,9.358420e+07,1.461430e+07,844600.000000,282300.000000,4.604000e+06,1.495500e+06,...,2.663600e+06,4.922500e+06,3.212300e+07,1.332000e+06,1.392000e+06,1.914900e+06,1.309300e+06,472800.000000,1.442500e+06,2.250100e+06

In [32]:
Stocks_companies.dtypes

Date           object
Attributes     object
A             float64
AAL           float64
AAP           float64
               ...
YUM           float64
ZBH           float64
ZBRA          float64
ZION          float64
ZTS           float64
Length: 400, dtype: object

In [51]:
df2 = pd.read_csv('yahoo_Stocks_companies.csv', index_col=0)  

df2.head()

,Date,Attributes,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
0,1/2/2020,Adj Close,85.552170,28.982893,158.410934,298.292145,86.008141,84.283539,168.809998,85.885757,...,61.569065,100.765846,68.567070,56.634895,79.849998,101.184380,148.520401,259.140015,51.462421,133.542831
1,1/3/2020,Adj Close,84.178558,27.548195,158.420868,295.392120,85.191757,83.223557,166.820007,84.838737,...,61.865166,98.446198,68.015823,56.008160,80.320000,100.867470,148.132172,256.049988,50.736221,133.562759
2,1/6/2020,Adj Close,84.427406,27.219410,155.817291,297.745880,85.864067,84.442039,179.039993,85.283234,...,61.776337,96.394203,68.538055,56.316555,79.800003,100.808052,147.276093,258.010010,50.117962,132.537338
3,1/7/2020,Adj Close,84.686203,27.119778,153.968964,296.345581,85.374245,83.837746,180.350006,84.809113,...,61.648026,98.594894,67.977135,56.614998,79.500000,100.986313,147.146683,256.470001,49.813740,132.985321
4,1/8/2020,Adj Close,85.522316,27.737495,152.200104,301.112640,85.979324,84.650070,178.690002,85.154816,...,61.588806,98.317329,66.952019,57.211887,79.769997,101.164581,148.908630,247.639999,50.304417,132.696609

In [52]:
df2['Date'] = pd.to_datetime(df2['Date'], format= '%m/%d/%Y')

In [65]:
df3 = df2.set_index(['Date'])

In [61]:
df2.to_csv('yahoo_Stocks_companies3.csv')

In [67]:
df2.dtypes

Date          datetime64[ns]
Attributes            object
A                    float64
AAL                  float64
AAP                  float64
                   ...
YUM                  float64
ZBH                  float64
ZBRA                 float64
ZION                 float64
ZTS                  float64
Length: 400, dtype: object

### Create Postgres Database

In [68]:
from sqlalchemy import create_engine

In [69]:
connection_string = "postgres:postgres@localhost:5432/stock_db"
engine = create_engine(f'postgresql://{connection_string}')

In [70]:
# Confirm tables
engine.table_names()

['stock_data', 'multicompany_data']

In [72]:
#Load database
df3.to_sql(name='all_company_stock', con=engine, if_exists='append', index=True)

In [ ]:
# a = df1.columns[1:507]
# close_df = df1.drop(df1.columns[1:507])
# close_df = df1.loc[df1[0:1013 == 'Close']

# close_df = df1.iloc[:,507:1013]
# high_df = df1.iloc[:,1013:1519]
# low_df = df1.iloc[:,1519:2025]
# open_df = df1.iloc[:,2025:2531]
# volume_df = df1.iloc[:,2531:3037]
# idx = np.r_[0:507,1013:3037]
# close_df = df1.drop(df1.columns[idx], axis=1, inplace=True)

# close_df = df1.iloc[df1.index.isin(closeslice_list)]
# rng = list(range[507:1013])
# close_df = df1.iloc[:, 507:1013]
# close_df = df1.drop(df1.columns[1:507])